import { Ingredient, SharingPost, SharingRecord, UserProfile } from '../types';

// Get current date string YYYY-MM-DD
const today = new Date();
const formatDate = (offsetDays: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split('T')[0];
};

export const INITIAL_USER: UserProfile = {
  id: 'user_1',
  name: '자취생 김소소',
  location: '서울 관악구 대학동',
  university: '서울대학교 인근 원룸촌',
  badgeLevel: '그린 쉐어러 🌿',
  totalSavedMoney: 48500,
  totalWastePreventedKg: 6.2,
  totalCo2PreventedKg: 15.5,
  completedShareCount: 8,
};

export const INITIAL_INGREDIENTS: Ingredient[] = [
  {
    id: 'ing_1',
    name: '대파 1단 (남은 4뿌리)',
    category: '채소/과일',
    quantity: '4뿌리',
    purchaseDate: formatDate(-5),
    expiryDate: formatDate(1), // D-1 Urgent!
    storage: '냉장',
    storageTip: '뿌리 부분을 송송 썰어 냉동 보관하면 한 달 이상 보관 가능해요.',
    priceEstimate: 3500,
    weightEstimateKg: 0.4,
    isShared: false,
    addedMethod: 'ai_scan',
  },
  {
    id: 'ing_2',
    name: '국산 콩두부 300g',
    category: '가공식품/양념',
    quantity: '1모 (미개봉)',
    purchaseDate: formatDate(-3),
    expiryDate: formatDate(2), // D-2 Warning
    storage: '냉장',
    storageTip: '개봉 후 밀폐용기에 깨끗한 물을 채우고 소금 한 꼬집을 넣으면 신선함이 오래 유지돼요.',
    priceEstimate: 2200,
    weightEstimateKg: 0.3,
    isShared: true,
    addedMethod: 'manual',
  },
  {
    id: 'ing_3',
    name: '신선한 무항생제 특란',
    category: '정육/계란',
    quantity: '6구 (10구 중 남음)',
    purchaseDate: formatDate(-2),
    expiryDate: formatDate(12), // D-12 Fresh
    storage: '냉장',
    storageTip: '뾰족한 부분이 아래로 가도록 란각에 보관하면 신선도가 높아집니다.',
    priceEstimate: 4500,
    weightEstimateKg: 0.36,
    isShared: false,
    addedMethod: 'ai_scan',
  },
  {
    id: 'ing_4',
    name: '서울우유 저지방 900ml',
    category: '음료/유제품',
    quantity: '500ml 남음',
    purchaseDate: formatDate(-1),
    expiryDate: formatDate(4), // D-4
    storage: '냉장',
    storageTip: '냉장고 문쪽보다는 온도가 일정한 안쪽 선반에 보관하세요.',
    priceEstimate: 2900,
    weightEstimateKg: 0.5,
    isShared: false,
    addedMethod: 'ai_scan',
  },
  {
    id: 'ing_5',
    name: '식빵 1봉 (6장 남음)',
    category: '베이커리/간식',
    quantity: '6장',
    purchaseDate: formatDate(-2),
    expiryDate: formatDate(2), // D-2
    storage: '상온',
    storageTip: '소분하여 랩에 싸서 냉동 보관한 뒤 토스터에 구우면 갓 구운 맛 그대로!',
    priceEstimate: 2800,
    weightEstimateKg: 0.3,
    isShared: false,
    addedMethod: 'manual',
  },
  {
    id: 'ing_6',
    name: '양파 묶음',
    category: '채소/과일',
    quantity: '3개',
    purchaseDate: formatDate(-7),
    expiryDate: formatDate(10),
    storage: '상온',
    storageTip: '스타킹이나 랩으로 하나씩 따로 감싸서 서늘하고 통풍 잘되는 곳에 두세요.',
    priceEstimate: 3000,
    weightEstimateKg: 0.6,
    isShared: false,
    addedMethod: 'ai_scan',
  },
];

export const INITIAL_SHARING_POSTS: SharingPost[] = [
  {
    id: 'post_1',
    title: '자취하느라 파 한 단 샀는데 반 단 나누어요! 🥬',
    ingredientName: '싱싱한 대파 반 단',
    category: '채소/과일',
    quantity: '약 5뿌리',
    storage: '냉장',
    expiryDate: formatDate(4),
    location: '대학동 (서울대 벤처타운역 2번출구)',
    distanceKm: 0.3,
    type: 'free',
    status: 'available',
    author: {
      id: 'author_1',
      name: '자취2년차',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
      area: '대학동',
    },
    createdAt: '10분 전',
    imageUrl: 'https://images.unsplash.com/photo-1618160702438-9b02ab6515c9?auto=format&fit=crop&w=600&q=80',
    description: '마트에서 대파 한 단을 어쩔 수 없이 묶음으로 구매했는데,혼자 다 못 먹어서 다듬어서 깨끗이 씻은 후 나눠드립니다! 입구에서 문고리 나눔도 가능해요.',
    likes: 5,
  },
  {
    id: 'post_2',
    title: '미개봉 스팸 200g 1캔 <-> 양파 2개와 교환해요',
    ingredientName: '스팸 클래식 200g',
    category: '가공식품/양념',
    quantity: '1캔 (미개봉)',
    storage: '상온',
    expiryDate: formatDate(180),
    location: '신촌동 (연세대 정문 앞)',
    distanceKm: 0.8,
    type: 'exchange',
    exchangeWant: '양파 2개 또는 감자 2개',
    status: 'available',
    author: {
      id: 'author_2',
      name: '연세자취러',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
      area: '신촌동',
    },
    createdAt: '35분 전',
    imageUrl: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=600&q=80',
    description: '명절 선물세트로 받은 스팸이 많은데 카레 만드느라 양파나 감자가 급하게 필요합니다. 깨끗한 재료와 교환 환영합니다!',
    likes: 8,
  },
  {
    id: 'post_3',
    title: '파스타면 500g 팩 절반 정도 남아있어요 🍝',
    ingredientName: '링귀니 파스타 면',
    category: '가공식품/양념',
    quantity: '약 250g (3회분)',
    storage: '상온',
    expiryDate: formatDate(90),
    location: '안암동 (고려대 안암역 3번출구)',
    distanceKm: 1.2,
    type: 'free',
    status: 'available',
    author: {
      id: 'author_3',
      name: '고대호랑이',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
      area: '안암동',
    },
    createdAt: '1시간 전',
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281862?auto=format&fit=crop&w=600&q=80',
    description: '본가로 한 달 동안 내려가게 되어서 유통기한 여유있는 파스타면 나눔합니다. 밀폐집게로 꽁꽁 싸매두었어요.',
    likes: 3,
  },
  {
    id: 'post_4',
    title: '유기농 귤 한 봉지 (약 10개) 나눠 드립니다! 🍊',
    ingredientName: '제주 노지 감귤',
    category: '채소/과일',
    quantity: '10개',
    storage: '상온',
    expiryDate: formatDate(5),
    location: '봉천동 (서울대입구역 5번출구)',
    distanceKm: 0.5,
    type: 'free',
    status: 'reserved',
    author: {
      id: 'author_4',
      name: '관악드림',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&q=80',
      area: '봉천동',
    },
    createdAt: '2시간 전',
    imageUrl: 'https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?auto=format&fit=crop&w=600&q=80',
    description: '부모님이 제주도에서 박스로 보내주셨는데 혼자 먹기엔 양이 많아 먼저 상하기 전에 이웃 자취생분들께 드립니다.',
    likes: 12,
  },
];

export const INITIAL_SHARING_RECORDS: SharingRecord[] = [
  {
    id: 'rec_1',
    postTitle: '방울토마토 1팩 나눔',
    ingredientName: '방울토마토',
    quantity: '약 300g',
    partnerName: '자취청년A',
    type: 'given',
    date: '2026-07-20',
    savedMoney: 4500,
    wastePreventedKg: 0.3,
    co2PreventedKg: 0.75,
  },
  {
    id: 'rec_2',
    postTitle: '진간장 500ml 절반 나눔받음',
    ingredientName: '진간장',
    quantity: '250ml',
    partnerName: '신림이웃',
    type: 'received',
    date: '2026-07-15',
    savedMoney: 3200,
    wastePreventedKg: 0.25,
    co2PreventedKg: 0.5,
  },
  {
    id: 'rec_3',
    postTitle: '카레용 돼지고기 소분 나눔',
    ingredientName: '돼지고기 등심',
    quantity: '200g',
    partnerName: '학식만족',
    type: 'given',
    date: '2026-07-08',
    savedMoney: 5800,
    wastePreventedKg: 0.2,
    co2PreventedKg: 1.8,
  },
  {
    id: 'rec_4',
    postTitle: '깐마늘 1봉지 나눔',
    ingredientName: '깐마늘',
    quantity: '150g',
    partnerName: '원룸주민',
    type: 'given',
    date: '2026-06-28',
    savedMoney: 3000,
    wastePreventedKg: 0.15,
    co2PreventedKg: 0.35,
  },
];

export const KOREA_NEIGHBORHOODS = [
  '관악구 대학동 (서울대 인근)',
  '관악구 봉천동 (서울대입구역)',
  '마포구 신촌동 / 서교동 (연세대/홍대)',
  '성북구 안암동 (고려대 인근)',
  '동대문구 회기동 (경희대/외대)',
  '동작구 흑석동 (중앙대 인근)',
  '광진구 화양동 (건국대 인근)',
  '서대문구 연희동',
];
